server:
  port: 8090

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-id: <CLIENT ID CONFIGURED IN GITHUB>
            client-secret: <CLIENT SECRET CONFIGURED IN GITHUB>
            scope: read:user
            redirect-uri: http://localhost:9080/login/oauth2/code/github
          #google:
            #provider: google
            #client-id: <CLIENT ID CONFIGURED IN GOOGLE>
            #client-secret: <CLIENT SECRET CONFIGURED IN GOOGLE>
            #scope: profile
            #redirect-uri: http://localhost:9080/login/oauth2/code/google
